version: "3.3"

services:
  app:
    build:
      context: .
    container_name: vue-app
    ports:
      - 8081:80
    networks:
      - internal

  nginx:
    image: nginx
    container_name: nginx-app
    volumes:
      - .nginx.conf:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - app

networks:
 internal: